#!/bin/bash
set -e

check_auth()
{
    logged_in=gh auth status &> /dev/null;
    return $logged_in;
}

clone_repo()
{
    # Check if user has logged in
    until check_auth();
    do
        gh auth login;
    done

    # Clone the repository if it exists otherwise fork it
    repo_matches=$(gh repo list --json name,parent --fork | jq '.[]' | jq '.name == $1 and .parent.owner.login == "python-discord"');
    readarray -t exists_list<<<"$repo_matches";

    # Check if the search results returned any matches
    exists="false";
    for match in "${exists_list[@]}
    do
        echo "TODO";   # TODO: continue
    done
}

